#!/bin/bash

###
### SIGliere
###
###  20260901-2300
###
###
###  Usage:  SIGliere [ACTION] [TARGET|DEVICE]
###
###       ACTION
###
###          install                install TARGET from current release
###          remove                 remove installed TARGET
###          purge                  remove installed TARGET and purge configs
###          build                  compile and install TARGET (option may not be available)
###          package                compile only and copy packaged to SIG/debs directory (option may not be available)
###          update                 check for TARGET updates
###          upgrade                upgrade TARGET to latest release
###
###          setup                  First time setup
###
###          list
###                 packages        List all packages included with SIGliere
###                 installed       List installed SIGliere packages
###                 library         List all packages included with SIGliere with installed ones marked with an *
###
###       TARGET
###
###          A SIGliere package
###


###
### INIT VARIABLES AND DIRECTORIES
###

# SIGliere directory tree
SIGLIERE_ROOT=~/SIGliere
SIGLIERE_SOURCE=$SIGLIERE_ROOT/source
SIGLIERE_ETC=$SIGLIERE_ROOT/etc
SIGLIERE_CONFIG=$SIGLIERE_ROOT/config
SIGLIERE_SCRIPTS=$SIGLIERE_ROOT/scripts
SIGLIERE_DEBS=$SIGLIERE_ROOT/debs

# SIGliere install support files
SIGLIERE_INSTALLED=$SIGLIERE_ETC/INSTALLED_PKGS
SIGLIERE_INSTALLED_SERVICES=$SIGLIERE_ETC/INSTALLED_SERVICES
SIGLIERE_BANNER_COLOR="\e[0;104m\e[K"   # blue
SIGLIERE_BANNER_RESET="\e[0m"

# Detect architecture (x86_64, ARMv8)
SIGLIERE_HWARCH=`lscpu|grep Architecture|awk '{print $2}'`
# Detect Operating system (Debian GNU/Linux 13 (Trixie) or Ubuntu 24.04 LTS)
SIGLIERE_OSNAME=`cat /etc/os-release|grep "PRETTY_NAME"|awk -F'"' '{print $2}'`
# Is Platform good for install- true or false - we start with false
SIGLIERE_CERTIFIED="false"
# What is the IP Address
SIGLIERE_IPADDR=`ip -br address | grep UP | awk '{print $1}'`


###
### FUNCTIONS
###

SIGEDGE_update(){
    # Check for available updates to package
    wget https://raw.githubusercontent.com/joecupano/SIGliere/main/packages/PACKAGES -P /tmp

    if grep $2 "/tmp/PACKAGES"; then
        SIG_PKGSTAMP=$(grep $2 "$SIGLIERE_ROOT/packages/PACKAGES"| cut -d,-f2)
        SIG_PKGNEW=$(grep $2 "/tmp/PACKAGES"| cut -d,-f2)
        if [ "$SIG_PKGNEW" != "$SIG_PKGSTAMP" ]; then
            echo "Update $SIG_PKGNEW is available"
        else
            echo "No updates available"
        fi
    fi
}

SIGEDGE_upgrade(){
    # Remove Package, update local clone, install updated package
    cd $SIGLIERE_ROOT
    source $SIGLIERE_ROOT/packages/$SPKGSCRIPT remove
    git pull
    source $SIGLIERE_ROOT/packages/$SPKGSCRIPT install
}

###
###  MAIN
###

ACTION=$1
SPACKAGE=$2
SPKGSCRIPT="pkg_$2"
SCFGSCRIPT="cfg_$2"

if [ "$1" = "device" ]; then
    SPKGSCRIPT="pkg_$3"
fi

case "$1" in
    setup )
        ## 1. Host prerequisites
        sudo ./scripts/install-os-packages.sh
        ./scripts/validate-os-packages.sh
        sudo ./scripts/install-corpus-dirs.sh

        ## 2. Ollama
        sudo ./scripts/install-ollama.sh
        ./scripts/validate-ollama.sh

        ## 3. SIGedge contract and gateway
        ./scripts/install-sigedge-gateway.sh

        ## 4. Open WebUI and Caddy
        if [ "$2" = "mycert" ]; then
            SIGLIERE_HOSTNAME=sigliere.example.com \
            SIGLIERE_CERT=/path/fullchain.pem \
            SIGLIERE_KEY=/path/privkey.pem \
            ./scripts/install-open-webui.sh
        else
            SIGLIERE_HOSTNAME=sigliere.example.local ./scripts/install-open-webui.sh
        fi

        ### Isolated, DNS-less network (IP-only addressing):
        SIGLIERE_HOSTNAME=$SIGLIERE_IPADDR ./scripts/install-open-webui.sh

        ## 5. Firewall and validation
        sudo ./scripts/install-security-hardening.sh
        ./scripts/validate-security-hardening.sh
        ./scripts/validate-tiered.sh

        ## 6. Open WebUI tools
        echo " "
        echo -e "${SIGLIERE_BANNER_COLOR} ##"
        echo -e "${SIGLIERE_BANNER_COLOR} ##  Follow openwebui-setup.md to install the native SIGedge"
        echo -e "${SIGLIERE_BANNER_COLOR} ##  status and operator tools and configure their tokens."
        echo -e "${SIGLIERE_BANNER_COLOR} ##"
        echo -e "${SIGLIERE_BANNER_RESET}"
        ;;

    list )
        if [ "$2" = "installed" ]; then
            echo " "
            echo -e "${SIGLIERE_BANNER_COLOR} ##"
            echo -e "${SIGLIERE_BANNER_COLOR} ##  SIGliere list installed"
            echo -e "${SIGLIERE_BANNER_COLOR} ##"
            echo -e "${SIGLIERE_BANNER_RESET}"
            echo " "
            echo -e "INSTALLED\t PACKAGE\t VERSION\t DESCRIPTION"
            echo " "
            awk 'BEGIN {FS=","} {printf "%-15s %-15s %-15s\n", $1, $2, $3}' $SIGLIERE_INSTALLED|more
        fi

        if [ "$2" = "packages" ]; then
            echo " "
            echo -e "${SIGLIERE_BANNER_COLOR} ##"
            echo -e "${SIGLIERE_BANNER_COLOR} ##  SIGliere list packages"
            echo -e "${SIGLIERE_BANNER_COLOR} ##"
            echo -e "${SIGLIERE_BANNER_RESET}"
            echo " "
            echo -e "PACKAGE\t VERSION\t DESCRIPTION"
            echo " "
            awk 'BEGIN {FS=","} {printf "%-15s %-15s %-15s\n", $1, $2, $3}' $SIGLIERE_PKGLIST|more
        fi

        if [ "$2" = "library" ]; then
                file1=$SIGLIERE_PKGLIST
                file2=$SIGLIERE_INSTALLED
                echo " "
                echo -e "${SIGLIERE_BANNER_COLOR} ##"
                echo -e "${SIGLIERE_BANNER_COLOR} ##  SIGliere list library"
                echo -e "${SIGLIERE_BANNER_COLOR} ##"
                echo -e "${SIGLIERE_BANNER_RESET}"
                echo " "
                echo -e "\tINSTALLED\t PACKAGE\t VERSION\t DESCRIPTION"
                while IFS= read -r line_file1
                do
                        if grep -qF "$line_file1" "$file2"; then
                                echo -e "*\t $line_file1"|awk 'BEGIN {FS=","} {printf "%-15s %-15s %-15s %-15s\n", " ", $1, $2, $3}'
                        else
                                echo -e " \t $line_file1"|awk 'BEGIN {FS=","} {printf "%-15s %-15s %-15s %-15s\n", " ", $1, $2, $3}'
                        fi
                done < "$file1"
        fi
        ;;

    build )
        source $SIGLIERE_PACKAGES/$SPKGSCRIPT build
        #sudo dpkg -i $SIGLIERE_DEBS/$2
        ;;

    package )
        source $SIGLIERE_PACKAGES/$SPKGSCRIPT package
        ;;

    remove )
        source $SIGLIERE_PACKAGES/$SPKGSCRIPT remove
        ;;

    purge )
        source $SIGLIERE_PACKAGES/$SPKGSCRIPT purge
        ;;

    install )
        source $SIGLIERE_PACKAGES/$SPKGSCRIPT install
        ;;
        
    update )
        SIGliere_update $3
        ;;

    upgrade)
        SIGliere_upgrade $3
        ;;

    * )
        cat <<EOF

  Usage:  SIGliere [ACTION] [TARGET|DEVICE]

       ACTION

          install                install TARGET from current release
          remove                 remove installed TARGET
          purge                  remove installed TARGET and purge configs
          build                  compile and install TARGET (option may not be available)
          package                compile only and copy packaged to SIG/debs directory (option may not be available)
          update                 check for TARGET updates
          upgrade                upgrade TARGET to latest release

          setup                  First time setup

          list
                 packages        List all packages included with SIGliere
                 installed       List installed SIGliere packages
                 library         List all packages included with SIGliere with installed ones marked with an *

       TARGET

          A SIGliere package

EOF
;;
esac

exit 0
