#!/bin/bash

###
### SIGliere_env
###
###  20260901-2300
###

###
### INIT VARIABLES AND DIRECTORIES
###

# SIGliere directory tree
SIGLIERE_ENV_FILE="$(readlink -f "${BASH_SOURCE[0]}")"
SIGLIERE_HOME="$(cd -- "$(dirname -- "$SIGLIERE_ENV_FILE")/.." && pwd)"
SIGLIERE_ROOT=$SIGLIERE_HOME
SIGLIERE_SOURCE=$SIGLIERE_ROOT/source
SIGLIERE_ETC=$SIGLIERE_ROOT/etc
SIGLIERE_CONFIG=$SIGLIERE_ROOT/config
SIGLIERE_SCRIPTS=$SIGLIERE_HOME/scripts
SIGLIERE_DEBS=$SIGLIERE_HOME/debs

# SIGliere install support files
SIGLIERE_INSTALLED=$SIGLIERE_ETC/INSTALLED_PKGS
SIGLIERE_INSTALLED_SERVICES=$SIGLIERE_ETC/INSTALLED_SERVICES
SIGLIERE_BANNER_COLOR="\e[0;104m\e[K"   # blue
SIGLIERE_BANNER_RESET="\e[0m"

# Detect architecture (x86_64, ARMv8)
SIGLIERE_HWARCH=`lscpu|grep Architecture|awk '{print $2}'`
# Detect Operating system (Debian GNU/Linux 13 (Trixie) or Ubuntu 24.04 LTS)
SIGLIERE_OSNAME=`cat /etc/os-release|grep "PRETTY_NAME"|awk -F'"' '{print $2}'`
# Is Platform good for install- true or false - we start with false
SIGLIERE_CERTIFIED="false"
# What is the IP Address
SIGLIERE_IPADDR=`ip -br address | grep UP | awk '{print $1}'`


